-- Завдання №1 - спроєктувати БД
-- Створи файл init_db.sql, у якому змоделюй структуру бази даних для компанії MegaSoft згідно брифінгу. Мають бути наступні таблиці:
--
-- worker - таблиця для працівників. У таблиці мають бути наступні поля:
-- ID - ідентифікатор працівника, ціле число, сурогатний первинний ключ.
-- NAME - ім'я працівника, рядок. Обмеження - не має бути NULL, довжина має бути від 2 до 1000 символів включно.
-- BIRTHDAY - дата народження. Рік у цій даті має бути більшим за 1900
-- LEVEL - рівень технічного розвитку працівника. Має бути обмеження - це поле не може бути NULL, значення поля може бути одним з - Trainee, Junior, Middle, Senior
-- SALARY - заробітна плата працівника за 1 місяць. Обмеження - ціле число, не менше 100 і не більше 100 000
-- client - таблиця для клієнтів. Мають бути наступні поля:
-- ID - ідентифікатор клієнта, ціле число, сурогатний первинний ключ.
-- NAME - ім'я працівника, рядок. Обмеження - не має бути NULL, довжина має бути від 2 до 1000 символів включно.
-- project - таблиця для проєктів. Мають бути наступні поля:
-- ID - ідентифікатор проєкту, ціле число, сурогатний первинний ключ.
-- CLIENT_ID - ідентифікатор клієнта, що замовив цей проєкт
-- START_DATE - дата початку виконання проєкту
-- FINISH_DATE - дата кінця виконання проєкту
-- project_worker - таблиця, що показує, які працівники над якими проєктами працюють. Поля таблиці:
-- PROJECT_ID - ідентифікатор проєкту. Зовнішній ключ для таблиці project(id)
-- WORKER_ID - ідентифікатор клієнту. Зовнішній ключ для таблиці worker(id)
-- первинний ключ для цієї таблиці - складений, пара (PROJECT_ID, WORKER_ID)

drop table if exists project_worker cascade;
drop table if exists project cascade;
drop table if exists worker cascade;
drop table if exists client cascade;

create table worker (
                        id int generated by default as identity primary key,
                        name varchar(1000) not null,
                        birthday date not null,
                        level varchar(20) not null,
                        salary int not null,

                        constraint chk_worker_name_len
                            check (char_length(name) between 2 and 1000),

                        constraint chk_worker_birthday_year
                            check (extract(year from birthday) > 1900),

                        constraint chk_worker_level
                            check (level in ('Trainee', 'Junior', 'Middle', 'Senior')),

                        constraint chk_worker_salary
                            check (salary between 100 and 100000)
);

create table client (
                        id int generated by default as identity primary key,
                        name varchar(1000) not null,

                        constraint chk_client_name_len
                            check (char_length(name) between 2 and 1000)
);

create table project (
                         id int generated by default as identity primary key,
                         name varchar(1000) not null,
                         client_id int not null,
                         start_date date not null,
                         finish_date date not null,

                         constraint chk_project_name_len
                             check (char_length(name) between 2 and 1000),

                         constraint fk_project_client
                             foreign key (client_id) references client(id),

                         constraint chk_project_dates
                             check (finish_date > start_date),

    -- duration: 1..100 months
                         constraint chk_project_duration_months
                             check (
                                 (
                                     extract(year from age(finish_date, start_date))::int * 12
                                         + extract(month from age(finish_date, start_date))::int
                                     ) between 1 and 100
                                 )
);

create table project_worker (
                                project_id int not null,
                                worker_id int not null,

                                constraint pk_project_worker
                                    primary key (project_id, worker_id),

                                constraint fk_pw_project
                                    foreign key (project_id) references project(id) on delete cascade,

                                constraint fk_pw_worker
                                    foreign key (worker_id) references worker(id)
);
